name: zkApp tests
on:
  push:
  pull_request:
  workflow_dispatch: {}
jobs:
  test:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        node: [18, 20]
        os: [ubuntu-latest]
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Git checkout
        uses: actions/checkout@v4
      - name: NPM ci, build, & test
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true
      - name: Run examples
        run: |
          echo "Running e2e example..."
          node build/src/examples/e2e.eg.js
          echo "Running escrow example..."
          node build/src/examples/escrow.eg.js
          echo "Running token-manager example..."
          node build/src/examples/token-manager.eg.js
          echo "Running side-loaded example..."
          node build/src/examples/side-loaded/run.js
        env:
          CI: true
